### ISSUE TITLE
>> SyntaxError: Unexpected identifier 'ng'

### ISSUE THREAD

**Issue by alscardoso** [tasuk/side-by-side#2]
once I run node_modules/.bin/grunt serve  I get the following error:

```
Running "jade:main" (jade) task
>> SyntaxError: Unexpected identifier 'ng'
Warning: Jade failed to compile source/index.html.jade. Use --force to continue
```

heads-up that I had to update a bunch of dependencies due to the fact that there new versions available, I wonder if this might be the reason.

Any ideas how to fix it? I'd love to be able to use this! Thank you

**Comment by alscardoso** [comment]
It looks like the issue was the node version that I was using. I swtiched to node 16 and it works! However now I see a bunch of critical vulnerabilities that do not fix with npm audit fix. Any suggestions?

**Comment by tasuki** [comment]
Hi @alscardoso! I'm afraid the dependencies are beyond repair now. Bower is obsolete, everything has moved on.

I wouldn't worry about critical vulnerabilities in this case: you aren't going to run this as a server or in any other capacity where it could get malicious input from the outside. It'll get input from you and spit out html/js and those are perfectly safe, because there's no backend!
